CREATE TABLE state (
                       id bigint primary key generated by default as identity,
                       name VARCHAR(255) NOT NULL,
                       country VARCHAR(255) NOT NULL,
                       created_by VARCHAR(100),
                       created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_by VARCHAR(100),
                       updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE city (
                      id bigint primary key generated by default as identity,
                      name VARCHAR(255) NOT NULL,
                      state_id BIGINT NOT NULL,
                      created_by VARCHAR(100),
                      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_by VARCHAR(100),
                      updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_city_state FOREIGN KEY (state_id) REFERENCES state(id)
);

CREATE TABLE zone (
                      id bigint primary key generated by default as identity,
                      name VARCHAR(255) NOT NULL,
                      city_id BIGINT NOT NULL,
                      latitude FLOAT,
                      longitude FLOAT,
                      created_by VARCHAR(100),
                      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_by VARCHAR(100),
                      updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_zone_city FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE users (
                       id bigint primary key generated by default as identity,
                       name VARCHAR(255) NOT NULL,
                       type VARCHAR(50) NOT NULL, -- (StateUser, CityUser, ZoneUser)
                       created_by VARCHAR(100),
                       created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_by VARCHAR(100),
                       updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_geo (
                          id bigint primary key generated by default as identity,
                          user_id BIGINT NOT NULL,
                          geo_id VARCHAR(255) NOT NULL,
                          created_by VARCHAR(100),
                          created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_by VARCHAR(100),
                          updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_user_geo_user FOREIGN KEY (user_id) REFERENCES users(id));
