
CREATE TABLE ss_master (
                            id BIGINT primary key generated by default as identity,
                            name VARCHAR(255) NOT NULL,
                            address VARCHAR(500) NOT NULL,
                            created_by VARCHAR(100),
                            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_by VARCHAR(100),
                            updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact (
                              id BIGINT primary key generated by default as identity,
                              contact_name VARCHAR(255) NOT NULL,
                              contact_number VARCHAR(50) NOT NULL,
                              ss_master_id BIGINT NOT NULL,
                              created_by VARCHAR(100),
                              created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_by VARCHAR(100),
                              updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT fk_contact_ems_master FOREIGN KEY (ss_master_id) REFERENCES ss_master(id)
);

ALTER TABLE zone add COLUMN radius FLOAT
